site_name: Datete Range Custom Template Variable
docs_dir: core/components/daterangetv/docs/mkdocs
site_dir: _build/site

repo_url: https://github.com/Jako/DaterangeTV

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'

theme: flatly

markdown_extensions:
    - footnotes
    - tables